id: P004262
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:05:43.803843
source_metadata:
  id: bdr:W8LS17243
  title: རྗེའི་གསང་བའི་རྣམ་ཐར།
  author: ''
  volumes:
    05f785fc26f146689d98b92c56f5c4de:
      image_group_id: I8LS17276
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
